function [fitresult, gof] = createFit(ratedhp, mpgcity)
%CREATEFIT1(RATEDHP,MPGCITY)
%  Create a fit.
%
%  Data for 'untitled fit 1' fit:
%      X Input : ratedhp
%      Y Output: mpgcity
%  Output:
%      fitresult : a fit object representing the fit.
%      gof : structure with goodness-of fit info.
%
%  See also FIT, CFIT, SFIT.

%  Auto-generated by MATLAB on 24-Apr-2019 11:17:13


%% Fit: 'untitled fit 1'.
[xData, yData] = prepareCurveData( ratedhp, mpgcity );

% Set up fittype and options.
ft = fittype( 'b1+b2/x', 'independent', 'x', 'dependent', 'y' );
opts = fitoptions( 'Method', 'NonlinearLeastSquares' );
opts.Display = 'Off';
opts.StartPoint = [0.655098003973841 0.162611735194631];

% Fit model to data.
[fitresult, gof] = fit( xData, yData, ft, opts );

% Plot fit with data.
figure( 'Name', 'untitled fit 1' );
h = plot( fitresult, xData, yData );
legend( h, 'mpgcity vs. ratedhp', 'untitled fit 1', 'Location', 'NorthEast', 'Interpreter', 'none' );
% Label axes
xlabel( 'ratedhp', 'Interpreter', 'none' );
ylabel( 'mpgcity', 'Interpreter', 'none' );
grid on


