function createfigure(X1, Y1)
%CREATEFIGURE1(X1, Y1)
%  X1:  scatter x
%  Y1:  scatter y

%  Auto-generated by MATLAB on 24-Apr-2019 10:53:23

% Create figure
figure1 = figure;

% Create axes
axes1 = axes('Parent',figure1);
hold(axes1,'on');

% Create scatter
scatter(X1,Y1);

% Create ylabel
ylabel({'mpg'});

% Create xlabel
xlabel({'rated hp'});

% Create title
title({'fuel economy'});

