function [fitresult, gof] = createFit2(cityhp, citympg)
%CREATEFIT2(CITYHP,CITYMPG)
%  Create a fit.
%
%  Data for 'untitled fit 1' fit:
%      X Input : cityhp
%      Y Output: citympg
%  Output:
%      fitresult : a fit object representing the fit.
%      gof : structure with goodness-of fit info.
%
%  See also FIT, CFIT, SFIT.

%  Auto-generated by MATLAB on 23-Apr-2019 22:30:17


%% Fit: 'untitled fit 1'.
[xData, yData] = prepareCurveData( cityhp, citympg );

% Set up fittype and options.
ft = fittype( 'b1+b2/x', 'independent', 'x', 'dependent', 'y' );
opts = fitoptions( 'Method', 'NonlinearLeastSquares' );
opts.Display = 'Off';
opts.StartPoint = [0.445586200710899 0.646313010111265];

% Fit model to data.
[fitresult, gof] = fit( xData, yData, ft, opts );

% Plot fit with data.
figure( 'Name', 'untitled fit 1' );
h = plot( fitresult, xData, yData );
legend( h, 'citympg vs. cityhp', 'untitled fit 1', 'Location', 'NorthEast', 'Interpreter', 'none' );
% Label axes
xlabel( 'cityhp', 'Interpreter', 'none' );
ylabel( 'citympg', 'Interpreter', 'none' );
grid on


