function dat = importfile2(workbookFile, sheetName, dataLines)
%IMPORTFILE2 Import data from a spreadsheet
%  DAT = IMPORTFILE2(FILE) reads data from the first worksheet in the
%  Microsoft Excel spreadsheet file named FILE.  Returns the data as a
%  table.
%
%  DAT = IMPORTFILE2(FILE, SHEET) reads from the specified worksheet.
%
%  DAT = IMPORTFILE2(FILE, SHEET, DATALINES) reads from the specified
%  worksheet for the specified row interval(s). Specify DATALINES as a
%  positive scalar integer or a N-by-2 array of positive scalar integers
%  for dis-contiguous row intervals.
%
%  Example:
%  dat = importfile2("C:\Users\ahaciogl\Desktop\CSUN\FuelEconomy-master-use this\fuelEconomyCurveFit\Final\dataXLS\2001dat.xlsx", "Sheet1", [2, 2434]);
%
%  See also READTABLE(.
%
% Auto-generated by MATLAB on 19-Nov-2019 10:25:20

%% Input handling

% If no sheet is specified, read first sheet
if nargin == 1 || isempty(sheetName)
    sheetName = 1;
end

% If row start and end points are not specified, define defaults
if nargin <= 2
    dataLines = [2, 2434];
end

%% Setup the Import Options and import the data
opts = spreadsheetImportOptions("NumVariables", 24);

% Specify sheet and range
opts.Sheet = sheetName;
opts.DataRange = "A" + dataLines(1, 1) + ":X" + dataLines(1, 2);

% Specify column names and types
opts.VariableNames = ["Year", "MfrName", "CarLine", "Car_Truck", "EngDisp", "Police", "RatedHP", "Transmission", "Drive", "Weight", "Comp", "AxleRatio", "EVSpeedRatio", "AC", "PRP", "FuelType", "City_Highway", "HC", "CO", "CO2", "NOX", "MPG", "Valves_Cyl", "CoastDownTime"];
opts.VariableTypes = ["double", "categorical", "categorical", "categorical", "double", "categorical", "double", "categorical", "categorical", "double", "double", "double", "double", "categorical", "double", "double", "categorical", "double", "double", "double", "double", "double", "double", "double"];

% Specify variable properties
opts = setvaropts(opts, ["MfrName", "CarLine", "Car_Truck", "Police", "Transmission", "Drive", "AC", "City_Highway"], "EmptyFieldRule", "auto");

% Import the data
dat = readtable(workbookFile, opts, "UseExcel", false);

for idx = 2:size(dataLines, 1)
    opts.DataRange = "A" + dataLines(idx, 1) + ":X" + dataLines(idx, 2);
    tb = readtable(workbookFile, opts, "UseExcel", false);
    dat = [dat; tb]; %#ok<AGROW>
end

end