function dat = importfile1(workbookFile, sheetName, dataLines)
%IMPORTFILE1 Import data from a spreadsheet
%  DAT = IMPORTFILE1(FILE) reads data from the first worksheet in the
%  Microsoft Excel spreadsheet file named FILE.  Returns the data as a
%  table.
%
%  DAT = IMPORTFILE1(FILE, SHEET) reads from the specified worksheet.
%
%  DAT = IMPORTFILE1(FILE, SHEET, DATALINES) reads from the specified
%  worksheet for the specified row interval(s). Specify DATALINES as a
%  positive scalar integer or a N-by-2 array of positive scalar integers
%  for dis-contiguous row intervals.
%
%  Example:
%  dat = importfile1("C:\Users\ahaciogl\Desktop\FuelEconomy-master-use this\fuelEconomyCurveFit\Final\dataXLS\2004dat.xlsx", "Sheet1", [2, 2338]);
%
%  See also READTABLE.
%
% Auto-generated by MATLAB on 02-May-2019 00:09:04

%% Input handling

% If no sheet is specified, read first sheet
if nargin == 1 || isempty(sheetName)
    sheetName = 1;
end

% If row start and end points are not specified, define defaults
if nargin <= 2
    dataLines = [2, 2338];
end

%% Setup the Import Options
opts = spreadsheetImportOptions("NumVariables", 24);

% Specify sheet and range
opts.Sheet = sheetName;
opts.DataRange = "A" + dataLines(1, 1) + ":X" + dataLines(1, 2);

% Specify column names and types
opts.VariableNames = ["Year", "MfrName", "CarLine", "Car_Truck", "EngDisp", "Police", "RatedHP", "Transmission", "Drive", "Weight", "Comp", "AxleRatio", "EVSpeedRatio", "AC", "PRP", "FuelType", "City_Highway", "HC", "CO", "CO2", "NOX", "MPG", "Valves_Cyl", "CoastDownTime"];
opts.SelectedVariableNames = ["Year", "MfrName", "CarLine", "Car_Truck", "EngDisp", "Police", "RatedHP", "Transmission", "Drive", "Weight", "Comp", "AxleRatio", "EVSpeedRatio", "AC", "PRP", "FuelType", "City_Highway", "HC", "CO", "CO2", "NOX", "MPG", "Valves_Cyl", "CoastDownTime"];
opts.VariableTypes = ["double", "categorical", "categorical", "categorical", "double", "categorical", "double", "categorical", "categorical", "double", "double", "double", "double", "categorical", "double", "double", "categorical", "double", "double", "double", "double", "double", "double", "double"];
opts = setvaropts(opts, [2, 3, 4, 6, 8, 9, 14, 17], "EmptyFieldRule", "auto");

% Import the data
dat = readtable(workbookFile, opts, "UseExcel", false);

for idx = 2:size(dataLines, 1)
    opts.DataRange = "A" + dataLines(idx, 1) + ":X" + dataLines(idx, 2);
    tb = readtable(workbookFile, opts, "UseExcel", false);
    dat = [dat; tb]; %#ok<AGROW>
end

end